name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            pip-

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies from both PyTorch and PyPI
        run: |
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pipenv install --deploy --dev
          
      - name: Run tests with coverage
        run: pipenv run pytest -n auto --junitxml=./test-reports/results.xml --cov=src --cov-report=term-missing:skip-covered | tee pytest-coverage.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-reports/results.xml

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results
          path: ./pytest-coverage.txt

  report:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./test-reports

      - name: Download Coverage Results
        uses: actions/download-artifact@v3
        with:
          name: coverage-results

      - name: Check if test reports exist
        run: ls -la ./test-reports

      - name: Display Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: ./test-reports/results.xml
          reporter: java-junit

      - name: Display Code Coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./test-reports/results.xml
