name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Clear pipenv cache
        run: pipenv --clear

      - name: Re-lock dependencies with pre-releases allowed
        run: pipenv lock --pre

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests with coverage
        if: success()
        run: pipenv run pytest --cov=src --cov-report=xml --junitxml=./test-reports/results.xml
      
      - name: Upload Test Results
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-reports/results.xml

      - name: Upload Coverage Results
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results
          path: ./coverage.xml

      - name: Display Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: ./test-reports/results.xml
          reporter: java-junit

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true