name: Run Cryptocurrency Analysis

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Cache pipenv dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pipenv-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          pipenv-

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --deploy --dev

    - name: Run the cryptocurrency analysis script
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SENDGRID_FROM_EMAIL: ${{ secrets.SENDGRID_FROM_EMAIL }}
        SENDGRID_TO_EMAIL: ${{ secrets.SENDGRID_TO_EMAIL }}
      run: pipenv run python main.py

  notify:
    runs-on: ubuntu-latest
    needs: build-and-run
    if: failure()

    steps:
    - name: Send error notification
      run: |
        echo "Error in the cryptocurrency analysis workflow. Check logs for details."
        # Optionally, send an email, Slack, or other notification
